#theme: jekyll-theme-hacker
theme: jekyll-theme-cayman

title: Julio Maqueda
description: it works on my machine

show_downloads: false

paginate: 10
paginate_path: "/posts/page:num/"

excerpt_separator: <!-- more -->
